#!/bin/sh
scdir=`dirname $0`
cd "$scdir"
if test -z "$1"; then
    docker run -d --rm -p 5005:5005 -v $(pwd):/app rasa/rasa:3.5.14-full run --enable-api --port 5005
else
    # e.g., for training
    docker run --rm --user $UID:$UID -v $(pwd):/app rasa/rasa:3.5.14-full "$@"
fi
